sudo: required
language: r
warnings_are_errors: false
dist: trusty
r: bioc-devel

r_packages:
  - devtools
  - rmarkdown

biocpackages:
  - SingleCellExperiment


cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.6 python3.6-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R -e 'Sys.setenv(PIP_QUIET=1); install.packages("tensorflow"); tensorflow::install_tensorflow(extra_packages="tensorflow-probability", version = "2.1.0", method="virtualenv")'
  - R -e 'tensorflow::tf_config()'

